name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    tags:
      - 'v*'

jobs:
  lint-eslint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint-eslint

  lint-prettier:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run lint-prettier

  publish-eslint:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-eslint')
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Configure NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
      - name: Extract version
        id: get_version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set version and publish eslint package
        run: |
          cd packages/eslint
          npm version $PACKAGE_VERSION --no-git-tag-version
          npm publish --access public

  publish-stylelint:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-stylelint')
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Configure NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
      - name: Extract version
        id: get_version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set version and publish stylelint package
        run: |
          cd packages/stylelint
          npm version $PACKAGE_VERSION --no-git-tag-version
          npm publish --access public

  publish-prettier:
    if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, '-prettier')
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Configure NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM }}" > ~/.npmrc
      - name: Extract version
        id: get_version
        run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Set version and publish prettier package
        run: |
          cd packages/prettier
          npm version $PACKAGE_VERSION --no-git-tag-version
          npm publish --access public
